apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: [ "--dockerfile=./nginx/Dockerfile",
            "--context=git://github.com/kangbock/kaniko.git#refs/heads/main",
            "--destination=kangbock/nginx",
            "--skip-tls-verify=true",
            "--insecure=true" ]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: docker-config-secret
        items:
          - key: .dockerconfigjson
            path: config.json
