apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEyRnVaMkp2WTJzNmNtdGtjV2h5TVRJaFFBPT0iCgkJfQoJfQp9"
type: kubernetes.io/dockerconfigjson
